version: '3.4'

services:
  logs:
    entrypoint:
    - '/bin/logspout'
    - '${LOGSPOUT_ENDPOINT}'

  js:
    image: samuelcolvin/mithra_js:latest

  backend:
    image: samuelcolvin/mithra_backend:latest

  web:
    image: samuelcolvin/mithra_web:latest

  nginx:
    build: nginx/prod
    restart: always
    ports:
    - 443:443
    depends_on:
    - logs
