version: '3.4'

services:
  logs:
    ports:
    - 5001:80

  web:
    build:
      context: src
      dockerfile: Dockerfile.web

  backend:
    build:
      context: src
      dockerfile: Dockerfile.backend

  nginx:
    image: samuelcolvin/nginx:1.13-alpine
    volumes:
    - ./nginx/dev/:/etc/nginx/conf.d/:ro
    - ./js/build/:/js-src/:ro
    ports:
    - 5000:80
