version: '3.4'

services:
  logs:
    ports:
    - 5001:80

  js:
    build: js

  web:
    build:
      context: src
      dockerfile: Dockerfile.web

  backend:
    build:
      context: src
      dockerfile: Dockerfile.backend

  nginx:
    build: nginx/dev
    restart: always
    ports:
    - 5000:80
