version: '3.4'

services:
  logs:
    entrypoint:
    - '/bin/logspout'
    - '${LOGSPOUT_ENDPOINT}'

  backend:
    image: samuelcolvin/mithra_backend:latest

  web:
    image: samuelcolvin/mithra_web:latest

  nginx:
    image: samuelcolvin/nginx:1.13-alpine
    volumes:
    - /home/ubuntu/nginx-conf/:/etc/nginx/conf.d/:ro
    - /home/ubuntu/js-src/:/js-src/:ro
    restart: always
    ports:
    - 443:443
    depends_on:
    - logs
