version: '3.4'

services:
  logs:
    ports:
    - 5001:80

#  nginx:
#    build: nginx/dev
#    restart: always
#    volumes:
#    - media:/media:ro
#    ports:
#    - 5000:80
#    depends_on:
#    - web
