#!/usr/bin/env bash
set -e

if [[ `docker info` = *"amazon"* ]]; then
  echo "you should build locally, not when connected to the remove docker machine"
  exit 1
fi

echo "================================================================================"
echo "building js..."
cd js
yarn build
cd ..
echo "================================================================================"
echo "building js done"
echo ""

export COMMIT="`git rev-parse --short HEAD`"

echo "================================================================================"
echo "building mithra_backend..."
docker build src/ -f src/Dockerfile.backend -t $DOCKER_ID_USER/mithra_backend:${COMMIT} -t $DOCKER_ID_USER/mithra_backend:latest
echo "================================================================================"
echo "building mithra_backend done"
echo ""

echo "================================================================================"
echo "building mithra_web..."
docker build src/ -f src/Dockerfile.web -t $DOCKER_ID_USER/mithra_web:${COMMIT} -t $DOCKER_ID_USER/mithra_web:latest
echo "================================================================================"
echo "building mithra_web done"
echo ""
echo "Pushing backend image:"
docker push $DOCKER_ID_USER/mithra_backend:${COMMIT}
docker push $DOCKER_ID_USER/mithra_backend:latest
echo "Pushing web image:"
docker push $DOCKER_ID_USER/mithra_web:${COMMIT}
docker push $DOCKER_ID_USER/mithra_web:latest
