#!/usr/bin/env bash
set -e
THIS_DIR=$(dirname "$0")

echo ""
echo "================================================================================"
echo "copying nginx and js files to machine..."

docker-machine scp -r -d $THIS_DIR/../nginx/prod/ $DOCKER_MACHINE_NAME:/home/ubuntu/nginx-conf/
docker-machine scp -r -d $THIS_DIR/../js/build/   $DOCKER_MACHINE_NAME:/home/ubuntu/js-src/

echo ""
echo "================================================================================"
echo "pulling new images..."

eval "${THIS_DIR}/compose pull backend web"

echo ""
echo "================================================================================"
echo "deploying new build..."
eval "${THIS_DIR}/compose up -d $@"
