#!/usr/bin/env bash
set -e
THIS_DIR=$(dirname "$0")

echo ""
echo "================================================================================"
echo "moving nginx and js files to machine..."

docker-machine scp -r -d $THIS_DIR/../nginx/prod/ mithra:/home/ubuntu/nginx-conf/
docker-machine scp -r -d $THIS_DIR/../js/build/ $MACHINE_NAME:/home/ubuntu/js-src/

echo ""
echo "================================================================================"
echo "pulling new images..."

eval "${THIS_DIR}/compose pull backend web"

echo ""
echo "================================================================================"
echo "deploying new build..."
# NOTICE: by default this doesn't build nginx/prod, you need to add --build for that
eval "${THIS_DIR}/compose up -d $@"
