FROM python:3.6-alpine

RUN apk --update --no-cache add gcc g++ musl-dev libuv libffi-dev make postgresql-dev \
 && rm -rf /var/cache/apk/*

RUN pip install -U pip setuptools
ADD ./requirements.txt /home/root/requirements.txt
RUN pip install -r /home/root/requirements.txt

ADD ./shared /home/root/shared
ADD ./backend/main.py /home/root/main.py
ADD ./backend/run.py /home/root/run.py

ENV PYTHONUNBUFFERED 1
WORKDIR /home/root
ENTRYPOINT ["./run.py"]
